language: python
python:
  - "3.6"      # current default Python on Travis CI
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - play-travis/test.py
notifications:
  slack:
    secure: xnQoUhvYcZEtjw7/Yawmu7TOCHk5VcreA3Hisav4cum9HqK/TwFn/8Rhalh+2YceCowZNIfz3+snjC/buer5fmj77rzCxY2GPmrNGX+/W0iZ3208U4FkOzKnSvQ4PCZEAPmRtfUqUNkSveW1gcpYf5UbhknRnULuRTT5dQo9TqSj4lrqXEQoWQUPG9eA3IBnSWx6Fu0uDPIRziKP5Aivwn1aOkFw+4IJnrFEedj8eLI49P+RDYOZFpoYG7dbeqow5fhZaiTLwcDPHZUGQEUOdeAzdH55Sq0JOUsV2k1LL/7GqVi2Fl3wtsc1a24EkbEU8rsf2xqBfdsc3+BD837P4WhEtqTwEXvwwdV1sp0NXaetl1zbksD7INuikCenXQ7ml666kwwn+UvgklnmgydMHvnK7INNuc2RLgYE+yF+hzNXhXX+M7T8pJ4igsc24Ri3kKN4qky1mf1/T8VHhkGUxHL+wQEZrZxzkb1JEiirL4PUyGvgg9pIqb5TEM1+NurI9gQzHW7yLEgl0/AMCRfYTlijVkuwAfQF9cXjHhJLIYMstyxsr6QMGDWCyJf9/WWwbpMVMjTMjkjbDH7owk/W/3Nnni4N69Ut2ybki2W3ssQCp60eT/8Fgxgsdki/vtNWROxBSnjkhhBH/GUOvREBVY34TI+DpY+zVxl2c76xsMQ=
