language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- play-travis/test.py
notifications:
  slack:
    rooms:
      secure: Dt70Ebfre1+r4hnd62UXmoX3QXc4rXczyzjpA3imMAS70IYHzaxvzdb0c/itRD/28L4W9UJzSxCBsIvMWGVus59KWU239nEXbf1A1iRfOO2cDub5TXgtjJycyaP4J0vHjFaTS7hSoUeHwXlqpWm6yokl/He6IgRYmHL7D6SWQTdb+0FcOAXHKV3ZYNe7Zt14F6wPC5NNpkZnLjFN4oWZ7QHVonomcL7y8qYH99YKuE3E5KQSqhp6M1Jqp6WRLX8fNWkheekJk8084gY0DZyUG1CqVuwObbUFx6umCnzTZpvZFCREPVqKCSStepnY1rVLGryyxQCh4hgHKs/A9cdNyU7Scl5kh64kJUD/7CBCYY9NVy10Zz997RoYUqlHnLYm/hh27dC+qxOTbwt33ut7Z+Uqh8Ur8sTltK4cZXpyvw98OBjiBHAOVW6H9TIrk3SVkQPC7f0LS/s00dEpJKgyldJzE1iinI+uTViTq8fbT+U2hqGYLo8tCoIZlkhYAxAgXMhKigCRtie01JqoWLl+OQQNCuq02WAM5+YqDv5x3G+eMv3o2/ZdJTdUKLoaw6kbCJAuxPaS28dh50CHCozI+4nmOrYEuTTdHYYjaDSwqBPwf8QDmP65XUH/myREXCeJ/KDir4WidfYcCfEZEhZcdyupGN0Mj8qEJncodkSrQaE=
