language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- play-travis/test.py
notifications:
  slack:
    rooms:
      secure: SKyiiUW/0zdjKWxmZdWnn4vDfyk//yOcSJIhs1P7j9V6wshXVgWchaHEm7YDlpRyqdEIdu1l7spCmaRV53Hbx3gHRuZ0tQ7L+hID8+8zbXpnqmDHWo5lZkdv/Gkw9f1Jd73Bc6oetkOVvFQQC378fzZfNXoWoHrWGWe8spzV/8+tTutRJcvtHY9mVuKkI3TDI5OOkI2q7SKmY/wNR9cD/BEcJ2C+xxOnsfIztrzZK3pq5WD0QeSSEa3i4QncaNnxk2+gd0427oxsiPZrxs5jthTJQG1Esx3vgOqdFvRIr2uZIKvVwO6ZJEvhfFYIVhGhmD2DyhdBDKVY8wSA3rmMppPd3QQQyoZb9EALjSoIgxhLnY5Fj6XsIcvuUGtIK2pTEH6PTpPnKqKhAp443YcMw2VFFB2X9M8VaJY+HQBmsDxIyKk6I9z8m4IeacFw/h774X+uwRUysf4kM0E98b++vXjWm64a7F1fVikBhyxRXTeGL9IeiOFOHj03pgV7iypLmN/SfTl8NlRO4QPpLD1pxi05spUPi7st0lV6kL2jFHL+a0d1uHADmo2k6OgnKdyrlPEkjF2MHa9cJ+R/ET0mIZoP/FLhJ4XR7u+8RlzHUqpDvhjEhwtASg6FtQq3zaepp2PowIqflZqvyiw5DPNC2nQ57hx9t/be2FUaaB2EPY0=
