language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- play-travis/test.py
notifications:
  slack:
    rooms:
      secure: JyPY9e+/GHQt8dxOGRuZvESSZ9VmbLzdcy12fgqzw/pILyeLc0iMUYBEFgW5a2SkEt5KYU59CGgLWbcSeWDGOmk/Na1Enxr98hVomNTGZIBpsGM2QKzzBAXe88OGMuMz77aIFaLNjp9iSASfaiDNoz+NLfdqB5CPR8AxlrXpcYD6xQUKxg+GqPqOokNB92TT2V+Mm5GuE3jh+pVr67W4CjM+6ucWJo/TZweJmsj1rzfC3gEXJaaFk0xtF49ves8x6JkrpkUSTtmMtsJETvXgphXnNQyDXyx0boo9gqydMn6n7HP8v47BNyHQjOGql02SlccAjY+nFwb2/Mtce5prmrK79cn+U5n6Epz9TF5cQePFoWND5JdNkZLE1/APVv9t+rw9JbulOZWS0ELnaZdv93LDFK9z9NlUSLfmiVTgDA0htESBnkubxvU7WFkjJq7la9Fs9vkdeIc738dvPq8GKM9cLVVmKPVO1k7ilyYFxcw+4klalgsu+FRuBLw/dPojfaczry2gcnwCtbFNYXt3MISeusnpL7rxg/EDHMtGz4b1sbr+R4cYvrzWBK/FQ9+8jSht3zR8Bjreca8zrRZv65KA27b13btW+3uRL3KrVTJD4f5AE6iNl3ZOWahNtD0k8gtMMYG1gFhbYsBHYzZSVBIdNR8QvQYw9mhjkEbNe9A=
