language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- play-travis/test.py
notifications:
  slack:
    rooms:
      secure: jJ+flrvt2a5AymGEN5DJzOfVCIlYjzI3LPB5qfRClPJbVN78ZFNsB77+7Htemw0Bj9Phonts8qDVO9ZSPtdI/jHe4qKNP0WBlA+lN3eslwXaYx5NKxAFQjp0vFop5vu3ffqfzQbcwSsATmYKLNo5nrAcC8ZtSPh3Md7kFrGQ5fmVu0y/JIA+QTpzVWuJkH+6uWQ/8C0d1vJtoH5tzu11irnrfk5mZGGvLb1MY7amwDWbW40i1E88Gn0GA1Gmn+lHI/4Mm0KaswP7Vhprez60cq25w6+EjXG3r0Y0F8Dy8U9Blx77C+5YXatZ8uVPquGgaziqWky6zqTPsl6gY/bIypyAOledIDn3GuEFPCLRoQoEJ1IzTNaQ2Y0ZOscPOhR1iVgM413B7RXCnAkNY8OO6FfiRy6bEcJXtCQqBVvYek/RFojGeeArneR0MZDPmTKMXtgC0lLUO+wC9L3BH+09sOTtSjxsch+YW1TBCR69PNCDAaZr8b8TyHRnneLorhjwkgcOBvc8KVvYLMuLBtcDULaCHckBDp9EWg64LNBp6Ov/+p7ne6YK8ytIQQgTSMk2eD53OrHDxKuzBafUVFCqcafYx1j2Cat5Z2WPjAw1/bki3wN31sBcHPzobA6AKBYgHDy3GlUMMKonDmtkH4yizKx+Qh3yKrqv7T0ym9ah/VM=
