language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- play-travis/test.py
notifications:
  slack:
    rooms:
      secure: DHxDr5tFHgQzEfYmZ4ZzV3GGZDC/GaXz5oTs0GCyipXCwTebEFFHq4nQUZSHRHWZmz0JzcvCKOlrW1dLCgFNS9rGvhhgl5TGn29bZuFM8Wy+CYeHmgEoYZGtm0jnqFioLfhUbbaHaZmeeDko9S8A/hm7s4LvalAmBl8M9O0p02L40um5kGF6GoUFEIa5uNUtd2Nh6VXaNcpx1baLkNxDJg1XQnlry9uth/8wToqAwjUs7k8Sb2F5gx74obDyknZHczn8qWvTjHq3WjRKpSQcmkyDwgFdKwwEmqceEwUi//4zh6KNugY2cMmoOH6wMX7nEuAF4O95a6maUYYsMIB1jvXrSqq1sdhjuxhbkAlC7zkuMm6l84mFGwqDl0Sx3Idd/keTzmsuTsGGci9e98wtOYmUXnsswACzWI+wR/gX+GSF4HckuHRNpXVt1umSnpwVRTzAncFSucQmj4mG4TDrgkPZcOWVEeTuaTG9LernQfI6NlHaxLNKBkO+EdrgWkZgr985fdNBr8sAxRO2EPnxov+ymXNlgxEJgSAGNi24K1nlJNcxUnpk96ifl0Htj1W5wbQw07DcvMaH4267tQWDq6Tj8WBmPCKE0XSZeQzulzxXkOedAAP8ubz9t5h4b3CBGCc+U2v7eRN2teKrRM8Rz6gPaTH61ksTIOuexovzSYQ=
