language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- play-travis/test.py
notifications:
  slack:
    rooms:
      secure: AQsnGhQwaI2apGqUhycpkZxe6nZP9+c6tPiWT4fOlqfCrxlYvW6eoKzJuh4275aVy+7yyO7JYL9C7/PiNUeHnmnwJ7xXqGk57wAY+kysbStpoqZh/VIsX4gKX4QUPi7c30mZfUDF3jiCeIg+fwvV/WwXMZKCPQwGChtvFwDgbkltZSnlTk5EISMXPPUQPgSeOBWyDFa32QkG927W0JVrij4AiGU6/j45SVnPa48OfrU35hpgxFGeMdiFkzuhKxjekRGPLkjcwaM5kfvLKnqu8htFaX0jTIilbaxBdw2fYcw4WUWXEtorwaZ9HCfgyGRe2h8S12pqvmXSItXLNaS5THaMex7RO0lAikqEwu9iGEDQ28Fb65mzVK3cSe2DjHuvIzPGXjYycnHgjw2VpjymlKRStJV/Bf+uX8SZaFau0+6o/MuyGOVsk+uTeJVhaGGlH3xktRv+bbjVGan+RJ9Yf1DWMmu44ja1s/ZE1XQmusVgC9nouOFu2E8dLD40wLMGDphPxEJcCrC2N4/duhJjdaSymbAB8lMgZL30yLofQF8ve93aFByPjSTjmeUc4h+sS+HREWdbNaKe3HVi3Zsv/FnzbU0wlkxXTFLan8TH6SDhIow4Y7mQPM1kXLLMftW7FFQJjN2GECuFbmLpfQoyBkjDzl2UEH5KGraQ81Bv6yY=
