language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- play-travis/test.py
notifications:
  slack:
    rooms:
      secure: NIUDJxPZqi9T+eQ1S0LklR6wU295t3d9pG6OwEI0870SRIuSxWkjzaq1OkVjts60QTjMMk4n52STT8RkLoMoJeHCPbD64ApUFi0oLXtBFIXZL17EyWVG74MmouZQtJpwzEnM7yrgzpVQzF4MJvEXwXlly97P2wrtWnOahEKNPoFQqCTDNdqUx9fwWh+K68aZXhiEnNGQNv9f/T61e1dnUccGH/I2+4JxKR6oiFMsS11c9BlR3hiiVs5salrtAykbAq++fgDTd8luCbHEJ3EVDhSC4XQK9UInTg2ql0bMdTkC2Su8Hv9UqQ1H+3EbeoHiCags6hLfDx4iHJKm0uUlfZ4KXctgO/8Am9Owt5MXe5iq156YLIFB5DWKnhChNYM/3izN2UF0XZvac2yEMOdVQwWcYxnvOvmbs7A0x7dEOUXSKHRAzBJKx7kwNKmP9mxa6FcnIt1eV3+OQuN6JTnxWcfgY7mwiBJPpo5ZZUMZCPAEaqC6eIAy7gfIY5J/2bACBTdvloVuYgsTMcUPDOIQid0m+iFGskjV0CFOhu71vaTf/NREYZfV6xiV6ah0H6rOaiDhZCf0d+NsjlwImC3b1QnlbRf8bcwpA1jiXgzz+azyOjBABcKzj8J1nIdJI4ulDfxstNAvmgWuvdpsgMPLe3R2p1/JjkvEYsIDRq01J8w=
