---
- name: Update cache
  apt:
    update_cache: yes
  tags: ruby

- name: Install ruby and rubygems and required packages
  apt: 
    pkg:
      - ruby-full
      - ruby-bundler
      - build-essential
    state: present
  tags: ruby
